name = "euclide-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# R2 Bucket Binding
[[r2_buckets]]
binding = "EUCLIDE_BUCKET"
bucket_name = "euclide-geometry"
preview_bucket_name = "euclide-geometry"

# KV Namespace Binding for Rate Limiting
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "656563deea8e49958294f5df78bc7c38"

# CORS headers
[vars]
ALLOWED_ORIGINS = "*"
